Repository jetstreamgg/webapp, pull requests merged in 2024-11, with the labels that each got.

#54 Fixes for the Safe connector issues
  package.json
  pnpm-lock.yaml
  src/data/wagmi/config/config.default.ts
  vite.config.ts
Labels: ready for review

#56 Update widget menu based on chain
  src/data/wagmi/config/config.default.ts
  src/modules/app/components/WidgetNavigation.tsx
  src/modules/app/components/WidgetPane.tsx
Labels: ready for review

#60 dev > staging
  package.json
  pnpm-lock.yaml
  src/data/wagmi/config/config.default.ts
  vite.config.ts
Labels: ready for review

#59 Fix container horizontal scroll on small screens
  src/data/wagmi/config/config.default.ts
  src/modules/layout/components/Header.tsx
Labels: ready for review

#63 Misc seal fixes
  package.json
  pnpm-lock.yaml
Labels: ready for review

#64 staging > main
  package.json
  pnpm-lock.yaml
Labels: ready for review

#61 Staging > main
  package.json
  pnpm-lock.yaml
  src/data/wagmi/config/config.default.ts
  vite.config.ts
Labels: ready for review

#62 Add SPK token logo
  src/public/tokens/spk.png
  src/public/tokens/spk.svg
Labels: ready for review

#66 Select the right urn in the details pane when opening the seal widget
  package.json
  pnpm-lock.yaml
  src/modules/seal/components/SealWidgetPane.tsx
Labels: ready for review

#67 Reorder sections in Seal details pane
  src/modules/seal/components/SealOverview.tsx
Labels: ready for review

#68 dev > staging
  package.json
  pnpm-lock.yaml
  src/modules/seal/components/SealOverview.tsx
  src/modules/seal/components/SealWidgetPane.tsx
  src/public/tokens/spk.png
  src/public/tokens/spk.svg
  src/test/e2e/tests/seal.spec.ts
  src/test/e2e/utils/approveOrPerformAction.ts
Labels: ready for review

#70 Fix widget content overflowing widget button on mobile
  src/modules/app/components/WidgetNavigation.tsx
Labels: ready for review

#69 staging > main
  package.json
  pnpm-lock.yaml
  src/modules/app/components/WidgetNavigation.tsx
  src/modules/seal/components/SealOverview.tsx
  src/modules/seal/components/SealWidgetPane.tsx
  src/public/tokens/spk.png
  src/public/tokens/spk.svg
  src/test/e2e/tests/seal.spec.ts
  src/test/e2e/utils/approveOrPerformAction.ts
Labels: ready for review

#75 Skip terms check if skip auth check is true
  src/modules/layout/components/AuthWrapper.tsx
  src/modules/ui/context/ConnectedContext.tsx
Labels: ready for review

#74 Initiate signing on checkbox click
  src/modules/ui/components/TermsModal.tsx
Labels: ready for review

#77 hook into widget state
  package.json
  pnpm-lock.yaml
  src/modules/config/context/ConfigContext.tsx
  src/modules/config/types/user-config.ts
  src/modules/seal/components/SealOverview.tsx
  src/modules/seal/components/SealPositionDetails.tsx
  src/modules/seal/components/SealPositionOverview.tsx
  src/modules/seal/components/SealWidgetPane.tsx
  src/modules/ui/components/BalanceCards.tsx
Labels: ready for review

#78 Add to seal test
  src/test/e2e/tests/seal.spec.ts
  tenderlyTestnetData.json
Labels: WIP

#80 show units in seal position overview
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
  src/modules/seal/components/SealPositionOverview.tsx
Labels: ready for review

#82 Refactor authentication and authorization logic
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
  src/modules/auth/components/UnauthorizedPage.tsx
  src/modules/layout/components/AuthWrapper.tsx
  src/modules/layout/components/CustomConnectButton.tsx
  src/modules/ui/context/ConnectedContext.tsx
Labels: ready for review

#83 Gp/copy updates
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
  src/modules/layout/components/ConnectCard.tsx
  src/modules/seal/getSealFaqItems.ts
  src/modules/ui/components/AboutSealModule.tsx
Labels: ready for review

#84 assets -> funds
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
  src/modules/balances/components/BalancesAssets.tsx
  src/modules/balances/components/BalancesDetails.tsx
  src/modules/balances/getBalancesFaqItems.ts
  src/modules/layout/components/ConnectCard.tsx
  src/modules/rewards/lib/getRewardsFaqItems.ts
  src/modules/savings/getSavingsFaqItems.ts
  src/modules/seal/getSealFaqItems.ts
  src/modules/ui/components/AboutCle.tsx
  src/modules/ui/components/PopoverRateInfo.tsx
  src/modules/upgrade/getUpgradeFaqItems.ts
Labels: ready for review

#81 dev > staging
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/lib/constants.ts
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
  src/modules/auth/components/UnauthorizedPage.tsx
  src/modules/balances/components/BalancesAssets.tsx
  src/modules/balances/components/BalancesDetails.tsx
  src/modules/balances/getBalancesFaqItems.ts
  src/modules/config/context/ConfigContext.tsx
  src/modules/config/types/user-config.ts
  src/modules/layout/components/AuthWrapper.tsx
  src/modules/layout/components/ConnectCard.tsx
  src/modules/layout/components/CustomConnectButton.tsx
  src/modules/rewards/lib/getRewardsFaqItems.ts
  src/modules/savings/getSavingsFaqItems.ts
  src/modules/seal/components/SealOverview.tsx
  src/modules/seal/components/SealPositionDetails.tsx
  src/modules/seal/components/SealPositionOverview.tsx
  src/modules/seal/components/SealWidgetPane.tsx
  src/modules/seal/getSealFaqItems.ts
  src/modules/ui/components/AboutCle.tsx
  src/modules/ui/components/AboutSealModule.tsx
  src/modules/ui/components/BalanceCards.tsx
  src/modules/ui/components/PopoverRateInfo.tsx
  src/modules/ui/components/TermsModal.tsx
  src/modules/ui/context/ConnectedContext.tsx
  src/modules/upgrade/getUpgradeFaqItems.ts
  src/test/e2e/tests/savings.spec.ts
  src/test/e2e/tests/seal.spec.ts
  tenderlyTestnetData.json
Labels: ready for review

#86 show seal rewards TVL in dollars
  src/modules/seal/components/SealRewardsOverview.tsx
Labels: ready for review

#89 fix messages
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
Labels: ready for review

#90 dev -> staging
  src/locales/en.po
  src/locales/es-AR.po
  src/locales/es-ES.po
  src/locales/es.po
  src/locales/ko.po
Labels: ready for review

#91 update chronicle faqs
  src/modules/rewards/lib/getRewardsCleFaqItems.ts
Labels: ready for review

#93 upgrade mkr
  src/modules/app/hooks/useActionForToken.tsx
  src/modules/balances/components/BalancesModuleShowcase.tsx
  src/modules/balances/components/BalancesSkyStatsOverview.tsx
  src/modules/config/default-config.ts
  src/modules/config/restrictedTokenList.ts
  src/modules/layout/components/ConnectCard.tsx
  src/modules/ui/components/UsdsSkyTotalsChart.tsx
  src/modules/ui/hooks/useUserSuggestedActions.ts
  src/modules/upgrade/components/UpgradeAbout.tsx
  src/modules/upgrade/components/UpgradeStats.tsx
  src/modules/upgrade/components/UpgradeWidgetPane.tsx
Labels: ready for review, do not merge

#96 development -> staging
  src/modules/app/hooks/useActionForToken.tsx
  src/modules/balances/components/BalancesModuleShowcase.tsx
  src/modules/balances/components/BalancesSkyStatsOverview.tsx
  src/modules/config/default-config.ts
  src/modules/config/restrictedTokenList.ts
  src/modules/layout/components/ConnectCard.tsx
  src/modules/ui/components/UsdsSkyTotalsChart.tsx
  src/modules/ui/hooks/useUserSuggestedActions.ts
  src/modules/upgrade/components/UpgradeAbout.tsx
  src/modules/upgrade/components/UpgradeStats.tsx
  src/modules/upgrade/components/UpgradeWidgetPane.tsx
Labels: ready for review

#97 Staging -> main
  src/modules/app/hooks/useActionForToken.tsx
  src/modules/balances/components/BalancesModuleShowcase.tsx
  src/modules/balances/components/BalancesSkyStatsOverview.tsx
  src/modules/config/default-config.ts
  src/modules/config/restrictedTokenList.ts
  src/modules/layout/components/ConnectCard.tsx
  src/modules/ui/components/UsdsSkyTotalsChart.tsx
  src/modules/ui/hooks/useUserSuggestedActions.ts
  src/modules/upgrade/components/UpgradeAbout.tsx
  src/modules/upgrade/components/UpgradeStats.tsx
  src/modules/upgrade/components/UpgradeWidgetPane.tsx
Labels: ready for review
